# Generated by Django 5.2.1 on 2026-02-01 06:11

import Notification.channel.mixins.notify_mixin
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('SMS', 'SMS'), ('EMAIL', 'Email')], max_length=15)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('QUEUED', 'Queued'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], help_text='current state of notification.', max_length=15)),
                ('category', models.CharField(choices=[('SUBSCRPTION', 'Subscription'), ('INVOICE', 'Invoice'), ('USER', 'User')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time the event was recorded.')),
                ('details', models.JSONField(default=dict, help_text='Stores the nested event path and dynamic data.')),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'abstract': False,
            },
            bases=(models.Model, Notification.channel.mixins.notify_mixin.EmailNotificationMixin),
        ),
    ]
