# Generated by Django 4.1.6 on 2025-02-09 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Services Categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True)),
                ('period', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('to_date', models.DateTimeField(default=datetime.datetime(9999, 12, 20, 0, 0))),
                ('current', models.BooleanField(default=True)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 19, 45, 47, 150596))),
                ('feature', models.ManyToManyField(to='ManagementSystem.feature')),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.service')),
                ('subscriptionType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubscriptionPlan', to='ManagementSystem.subscriptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Subscription', to='ManagementSystem.client')),
                ('subscriptionPlan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Subscription', to='ManagementSystem.subscriptionplan')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.servicescategory'),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('client', models.ManyToManyField(blank=True, related_name='Representative', to='ManagementSystem.client')),
            ],
        ),
        migrations.CreateModel(
            name='Recipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionPlan', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('None', 'None'), ('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled')], default='NONE', max_length=15)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Recipt', to='ManagementSystem.client')),
                ('representative', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Recipt', to='ManagementSystem.representative')),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='servicesCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManagementSystem.servicescategory'),
        ),
        migrations.AddField(
            model_name='client',
            name='representative',
            field=models.ManyToManyField(blank=True, related_name='Client', to='ManagementSystem.representative'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='Client', to='ManagementSystem.subscription'),
        ),
    ]
