# Generated by Django 5.2.1 on 2025-10-18 10:45

import ManagementSystem.Mixins.Time
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void'), ('UNCOLLECTABLE', 'Uncollectable')], default='Draft', max_length=15)),
                ('created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('days', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=30)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.period')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('default_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.pricelist')),
                ('price_list', models.ManyToManyField(related_name='product_%(class)s_related', to='ManagementSystem.pricelist')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.invoice')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.product')),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('client', models.ManyToManyField(blank=True, related_name='Representative', to='User.client')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15)),
                ('begin', models.DateTimeField(default=datetime.datetime(2025, 10, 18, 10, 45, 5, 225018, tzinfo=datetime.timezone.utc), null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('trial', models.PositiveIntegerField(default=0)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_approved_by', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Subscription', to='User.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_created_by', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_rejected_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_approve_subscription', 'Can approve subscription')],
            },
            bases=(models.Model, ManagementSystem.Mixins.Time.Time),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='ManagementSystem.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('PAUSED', 'PAUSED')], default='DEACTIVE', max_length=15)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plan_%(class)s_related', to='ManagementSystem.pricelist')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plan_%(class)s_related', to='ManagementSystem.product')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='ManagementSystem.subscription')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, ManagementSystem.Mixins.Time.Time),
        ),
    ]
