# Generated by Django 5.2.1 on 2025-06-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='apporved',
            field=models.BooleanField(default=False),
        ),
    ]
