# Generated by Django 4.1.6 on 2025-03-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('days', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=30)),
                ('unit_period', models.PositiveIntegerField(default=1)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.period')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='current',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='expiry',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='subscriptionType',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='to_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='active_plans',
            field=models.ManyToManyField(blank=True, related_name='ActiveSubscriptionPlan', to='ManagementSystem.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='begin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='deactive_plans',
            field=models.ManyToManyField(blank=True, related_name='DeactiveSubscriptionPlan', to='ManagementSystem.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.service'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='SubscriptionType',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='PriceList',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SubscriptionPlan', to='ManagementSystem.pricelist'),
        ),
    ]
