# Generated by Django 5.2.1 on 2025-06-09 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='Product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plan_%(class)s_related', to='ManagementSystem.product'),
        ),
    ]
