# Generated by Django 5.2.1 on 2026-02-16 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManagementSystem', '0001_initial'),
        ('User', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='User.client'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_detail', to='ManagementSystem.invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManagementSystem.currency', verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagementSystem.period', verbose_name='period'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.pricelist', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.pricelist', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ManyToManyField(related_name='product_%(class)s_related', to='ManagementSystem.pricelist', verbose_name='Price_list'),
        ),
        migrations.AddField(
            model_name='invoicedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='representative',
            name='client',
            field=models.ManyToManyField(blank=True, related_name='Representative', to='User.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved_by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Subscription', to='User.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created_by'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_rejected_by', to=settings.AUTH_USER_MODEL, verbose_name='Rejected_by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='ManagementSystem.subscription', verbose_name='Subscription'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plan_%(class)s_related', to='ManagementSystem.pricelist', verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plan_%(class)s_related', to='ManagementSystem.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='ManagementSystem.subscription', verbose_name='Status'),
        ),
    ]
