# Generated by Django 4.1.6 on 2025-03-04 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0002_period_pricelist_remove_client_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscriptionPlan',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
