# Generated by Django 5.2.1 on 2025-06-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0002_alter_subscriptionplan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('DEACTIVE', 'Deactive'), ('EXPIRED', 'Expired'), ('ENDED', 'Ended')], default='DRAFT', max_length=15, primary_key=True, serialize=False),
        ),
    ]
