# Generated by Django 4.1.6 on 2025-03-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0003_remove_subscription_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipt',
            name='subscriptionPlan',
        ),
        migrations.AddField(
            model_name='recipt',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Recipt', to='ManagementSystem.subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipt',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('RENEW', 'Renew')], default='NONE', max_length=15),
        ),
    ]
