# Generated by Django 5.2.1 on 2025-06-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0003_remove_subscriptionplan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='PriceList',
            field=models.ManyToManyField(related_name='product_%(class)s_related', to='ManagementSystem.pricelist'),
        ),
    ]
