# Generated by Django 5.2.1 on 2025-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0003_subscription_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('DEACTIVE', 'Deactive'), ('EXPIRED', 'Expired')], default='DEACTIVE', max_length=15),
        ),
    ]
