# Generated by Django 5.2.1 on 2025-06-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0004_alter_subscriptionplan_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='apporved',
            new_name='approved',
        ),
    ]
