# Generated by Django 5.2.1 on 2025-06-09 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0004_remove_pricelist_product_product_pricelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PriceList',
            new_name='price_list',
        ),
        migrations.AddField(
            model_name='product',
            name='default_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ManagementSystem.pricelist'),
        ),
    ]
