# Generated by Django 4.1.6 on 2025-03-04 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0004_remove_recipt_subscriptionplan_recipt_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('None', 'None'), ('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('RENEW', 'Renew')], default='NONE', max_length=15)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='ManagementSystem.client')),
                ('representative', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Invoice', to='ManagementSystem.representative')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Invoice', to='ManagementSystem.subscription')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipt',
        ),
    ]
