# Generated by Django 5.2.1 on 2025-06-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0005_rename_pricelist_product_price_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.pricelist'),
        ),
    ]
