# Generated by Django 4.1.6 on 2025-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0006_invoice_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
