# Generated by Django 5.2.1 on 2025-06-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0006_alter_product_default_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ManagementSystem.pricelist'),
        ),
    ]
