# Generated by Django 4.1.6 on 2025-03-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagementSystem', '0007_invoice_due_date_alter_invoice_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Subscription', to='ManagementSystem.client'),
        ),
    ]
