# Generated by Django 5.2.1 on 2025-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_subscription', 'Can create subscription without approval')]},
        ),
    ]
