# Generated by Django 4.1.6 on 2025-03-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.user',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('User.user',),
        ),
    ]
