# Generated by Django 5.2.1 on 2025-06-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_subscription', 'Can create subscription without approval'), ('can_approve_subscription', 'Can approve subscription')]},
        ),
    ]
